#!/usr/bin/env python3
import npyscreen

class MainForm(npyscreen.FormBaseNew):
    def create(self):
        self.add(npyscreen.TitleText, name="Text:", value="Hello, World!")
        self.add(npyscreen.TitlePassword, name="Password:")
        self.add(npyscreen.TitleFilename, name="Filename:")
        self.add(npyscreen.ButtonPress, name="Press Me", when_pressed_function=self.on_press)

    def on_press(self):
        npyscreen.notify_confirm("Button pressed!")

class MyApp(npyscreen.NPSAppManaged):
    def onStart(self):
        self.addForm("MAIN", MainForm, name="My Npyscreen Application")

if __name__ == "__main__":
    app = MyApp()
    app.run()
