#!/usr/bin/env python3
from PyInquirer import prompt
import os
from typing import Any
from colorama import init
from termcolor import colored
from urllib.parse import urljoin
import datetime
import requests
import json
init()

URL = "http://localhost:8080/"
DATE_FORMAT = "%d-%m-%Y %H:%M"

def cls():
    if os.name == "nt":
        os.system("cls")
    else:
        os.system("clear")

def printe(*msgs: object):
    for msg in msgs:
        msg = str(msg)
        [print(f"{colored('ERROR  ', 'red')}: {line}") for line in msg.split('\n')]

def printw(*msgs: object):
    for msg in msgs:
        msg = str(msg)
        [print(f"{colored('WARNING', 'yellow')}: {line}") for line in msg.split('\n')]

def printl(*msgs: object):
    for msg in msgs:
        msg = str(msg)
        [print(f"{colored('LOG    ', 'green')}: {line}") for line in msg.split('\n')]

def enter_to_continue():
    input("Press <Enter> to continue...")

def ask_for_date(msg: str) -> str:
    while True:
        date_str = input(msg)
        try:
            datetime.datetime.strptime(date_str, DATE_FORMAT)
            return date_str
        except:
            printw(f"La fecha que has escrito no sigue el formato que se requiere ({DATE_FORMAT})")

def do_request(endpoint: str, method: str, url_params: dict[str, Any] = {}):
    target_url = urljoin(URL, endpoint)
    res: requests.Response
    try:

        match method.lower():
            case "get":
                res = requests.get(target_url, params=url_params)
            case "post":
                res = requests.post(target_url, params=url_params)
            case "delete":
                res = requests.delete(target_url, params=url_params)
            case "put":
                res = requests.put(target_url, params=url_params)
            case _:
                raise Exception(f"'{method}' is not recognized as a valid method")
    except Exception as e:
        printe(f"An error has occurred: {e}")
        return

    printl(f"=======> {colored(method, 'green')} request to '{colored(res.url, 'green')}'")
    printl(f"Status code: {colored(res.status_code, 'green' if res.status_code == 200 else 'red')}")

    if res.headers.get("Content-Type", "") == "application/json":
        printl("==> Json contents of the response: ")
        printl(json.dumps(res.json(), indent=2))
    else:
        printl("==> Body of the response: ")
        printl(res.content.decode("utf-8"))

# ###############
# Request methods
# ###############

def query_all_rooms():
    do_request("/salas/", "get")
    enter_to_continue()

def query_room_by_id():
    question = [
        {
            "type": "input",
            "name": "id",
            "message": "ID de la sala: ",
            "default": "1"
        }
    ]
    do_request(f"/salas/{prompt.prompt(question)['id']}", "get")
    enter_to_continue()

def create_room():
    questions = [
        {
            "type": "input",
            "name": "name",
            "message": "Nombre de la sala:",
            "default": "Sala de reuniones"
        },
        {
            "type": "input",
            "name": "capacity",
            "message": "Capacidad de la sala:",
            "default": "20"
        },
        {
            "type": "input",
            "name": "location",
            "message": "Ubicacion de la sala:",
            "default": "A2"
        },
    ]
    answers = prompt.prompt(questions)
    params = {
        "name": answers['name'],
        "capacity": answers['capacity'],
        "location": answers['location']
    }
    do_request(f"/salas/", "post", params)
    enter_to_continue()

def update_room():
    questions = [
        {
            "type": "input",
            "name": "room_id",
            "message": "ID de la sala a modificar:"
        },
        {
            "type": "input",
            "name": "name",
            "message": "Nombre de la sala:",
        },
        {
            "type": "input",
            "name": "capacity",
            "message": "Capacidad de la sala:",
        },
        {
            "type": "input",
            "name": "location",
            "message": "Ubicacion de la sala:",
        },
    ]
    answers = prompt.prompt(questions)
    params = {
        "name": answers['name'],
        "capacity": answers['capacity'],
        "location": answers['location']
    }
    do_request(f"/salas/{answers['room_id']}", "put", params)
    enter_to_continue()

def delete_room():
    room_id = input("ID de la sala a eliminar: ")
    do_request(f"/salas/{room_id}", "delete")
    enter_to_continue()

def query_all_bookings():
    do_request(f"/reservas/", "get")
    enter_to_continue()

def query_booking_by_id():
    booking_id = input("ID de la reserva: ")
    do_request(f"/reservas/{booking_id}", "get")
    enter_to_continue()

def create_booking():
    questions = [
        {
            "type": "input",
            "name": "room_id",
            "message": "ID de la sala a reservar:"
        },
        {
            "type": "input",
            "name": "organizer",
            "message": "Nombre del organizador:",
        },
        {
            "type": "input",
            "name": "start_date",
            "message": "Fecha de comienzo de la reserva:",
        },
        {
            "type": "input",
            "name": "end_date",
            "message": "Fecha de final de la reserva:",
        },
    ]
    answers = prompt.prompt(questions)

    do_request(
        f"/reservas/",
        "post",
        {
            "roomId": answers['room_id'],
            "organizer": answers['organizer'],
            "startDate": answers['start_date'],
            "endDate": answers['end_date']
        }
    )
    enter_to_continue()

def update_booking():
    questions = [
        {
            "type": "input",
            "name": "booking_id",
            "message": "ID de la reserva a modificar:"
        },
        {
            "type": "input",
            "name": "room_id",
            "message": "ID de la sala a reservar:"
        },
        {
            "type": "input",
            "name": "organizer",
            "message": "Nombre del organizador:",
        },
        {
            "type": "input",
            "name": "start_date",
            "message": "Fecha de comienzo de la reserva:",
        },
        {
            "type": "input",
            "name": "end_date",
            "message": "Fecha de final de la reserva:",
        },
    ]
    answers = prompt.prompt(questions)
    do_request(
        f"/reservas/{answers['booking_id']}",
        "put",
        {
            "roomId": answers['room_id'],
            "organizer": answers['organizer'],
            "startDate": answers['start_date'],
            "endDate": answers['end_date']
        }
    )
    enter_to_continue()

def delete_booking():
    booking_id = input("ID de la reserva a borrar: ")
    do_request(f"/reservas/{booking_id}", "delete")
    enter_to_continue()

def query_booking_by_room_id():
    room_id = input("ID de la sala: ")
    do_request(f"/reservas/sala/{room_id}", "get")
    enter_to_continue()

def main():
    opciones = [
        "Obtener salas",
        "Obtener sala por ID",
        "Crear sala",
        "Actualizar sala",
        "Eliminar sala",
        "Obtener todas las reservas",
        "Obtener reserva por ID",
        "Crear reserva",
        "Actualizar reserva",
        "Borrar reserva",
        "Obtener reservas para una sala",
        "Salir"
    ]
    prompt_questions = [
        {
            "type": "list",
            "name": "option",
            "message": "Selecciona una opcion",
            "choices": opciones,
        },
    ]

    while True:
        cls()
        print(f"====> {colored('CLIENTE DE GESTION DE SALAS Y RESERVAS', 'green')}")
        opcion = opciones.index(prompt.prompt(prompt_questions)["option"])
        match opcion:
            case 0:
                # "Obtener salas",
                query_all_rooms()
            case 1:
                # "Obtener sala por ID",
                query_room_by_id()
            case 2:
                # "Crear sala",
                create_room()
            case 3:
                # "Actualizar sala",
                update_room()
            case 4:
                # "Eliminar sala",
                delete_room()
            case 5:
                # "Obtener todas las reservas",
                query_all_bookings()
            case 6:
                # "Obtener reserva por ID",
                query_booking_by_id()
            case 7:
                # "Crear reserva",
                create_booking()
            case 8:
                # "Actualizar reserva",
                update_booking()
            case 9:
                # "Borrar reserva",
                delete_booking()
            case 10:
                # "Obtener reservas para una sala"
                query_booking_by_room_id()
            case 11:
                exit()

if __name__ == "__main__":
    main()
